name = "youtube-websub-worker"
main = "src/index.js"
compatibility_date = "2024-03-01"

[triggers]
crons = [ "0 0 * * *" ] # Run once a day at midnight UTC to renew WebSub subscription

[vars]
CHANNEL_ID = "UCLKPca3kwwd-B59HNr-_lvA"
GITHUB_OWNER = "briannoelkesuma"
GITHUB_REPO = "ai_engineer_newsletter"
WORKER_URL = "https://youtube-websub-worker.2612brian.workers.dev"
